Функции и Массивы
js-tasks-ru/jsbasic-20220901_eldashdamirov pull request #4
Opened 2022-09-15 11:23 UTC by Ellbrus

2022-09-15 11:24 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-15 15:21 UTC, SinimaWath requested changes

2022-09-15 15:21 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return arrNames;
Если используешь map, то тебе не нужен push:
`return users.map(() => <И здесь вернуть новое значение>)`

2022-09-15 15:21 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  return string.slice(0, -1);
Давай попробуем вот такую комбинацию:
```
users
  .filter()
  .map()
  .join('\n')
```

2022-09-17 13:31 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-09-19 09:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-09-19 11:24 UTC, SinimaWath approved these changes

2022-09-19 11:25 UTC, merged